### ISSUE TITLE
独自CSSとBootstrapのCSSがかぶってる

### ISSUE THREAD

**Issue by shinbunbun** [shinbunbun/shinbunbun.github.io#65]
https://github.com/shinbunbun/shinbunbun.github.io/blob/d7e4a971dafea91244dc1e5ab9e44481163ce666/components/HomeCard.vue#L125-L130

**Comment by u7693** [comment]
https://github.com/shinbunbun/shinbunbun.github.io/blob/d7e4a971dafea91244dc1e5ab9e44481163ce666/components/MyHeader.vue#L75-L79

**Comment by u7693** [comment]
https://github.com/shinbunbun/shinbunbun.github.io/blob/d7e4a971dafea91244dc1e5ab9e44481163ce666/components/ProductCard.vue#L50-L56
